### ISSUE TITLE
unprivileged users see broken content blocks in CMS interface 

### ISSUE THREAD

**Issue by katieelks** [silverstripe/silverstripe-elemental#311]
(low priority) issue where pages using content blocks look broken in the CMS interface to users without permissions to edit that page.
Wondering if anyone else has had a similar issue or if it's something we've done?
![screen shot 2018-08-03 at 12 22 02 pm](https://user-images.githubusercontent.com/38870753/43928521-4c1640ec-9c85-11e8-8d1b-63c7337ce29b.png)
![screen shot 2018-08-03 at 12 21 57 pm](https://user-images.githubusercontent.com/38870753/43928522-4d35c538-9c85-11e8-8b43-396cc0fa80b6.png)

**Comment by NightJar** [comment]
Hi @katieelks 

Unfortunately this looks like a semi-intentional side effect from a `readonlyTransformation` on the `ElementalAreaField`, introduced as part of the work for seeing content history for a Page that houses its content in Elements (details in https://github.com/dnadesign/silverstripe-elemental/issues/181).

The long and short is that the `getCMSFields` on each block are rendered out as `readonly` via https://github.com/dnadesign/silverstripe-elemental/pull/224/files#diff-70360ce019aa6acd3b9670bd2c56b9cfR67

In order to change this, custom field types can define a `performReadonlyTransformation` function that can then exert control over how the output looks. These are the `FormField`s that are defined on an Element - I'm looking more at Events than what appears to be `UploadField`s for the news sections.

**Comment by robbieaverill** [comment]
I don't think we should call this a feature. @katieelks can you please provide some example code (via DM if you want to keep it off GitHub) so we can see how the element code is structured?

IMO this shouldn't happen - bug

**Comment by maxime-rainville** [comment]
Don't think this is relevant anymore.
