### ISSUE TITLE
Make core Actions in ActionMenu more flexible

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-elemental#755]
To reduce complexity for CMS authors, some projects may wish to disable publishing at the block level and instead keep it at the Page level. So how would a developer go about removing the Publish / Unpublish actions from the ElementEditor UI?

Elemental currently employs the following code to render the ElementActions menu (the ellipsis menu on each block that allows you to switch tab or perform save actions):

_client/src/components/ElementEditor/ElementActions.js_
```jsx
      <ActionMenuComponent
        id={`element-editor-actions-${id}`}
        className={'element-editor-header__actions-dropdown'}
        dropdownMenuProps={{ right: true }}
        dropdownToggleClassNames={dropdownToggleClassNames}
      >
        { this.renderEditTabs() }
        { this.renderDivider() }
        { children } {/* Save/publish actions are passed in and rendered */}
      </ActionMenuComponent>
```

Then, to populate `{ children }`, each save action (`SaveAction`, `ArchiveAction`, `PublishAction`, `UnpublishAction`) is written so that it can be [HOC](https://reactjs.org/docs/higher-order-components.html)'d onto the `ActionMenu` using Injector:

_client/src/boot/registerTransforms.js_
```
  Injector.transform('element-actions', (updater) => {
    updater.component('ElementActions', SaveAction, 'ElementActionsWithSave');
    updater.component('ElementActions', PublishAction, 'ElementActionsWithPublish');
    updater.component('ElementActions', UnpublishAction, 'ElementActionsWithUnpublish');
    updater.component('ElementActions', ArchiveAction, 'ElementActionsWithArchive');
  });
```

This successfully renders the menu, and it's fairly trivial to _add_ new actions by adding additional HOCs. Unfortunately, it also makes it nigh-impossible to _remove_ any individual existing actions. You'd need to register a HOC that is applied after the action you want to remove, peek into the nested array in the `children` prop and manually pluck out the action(s) you want to remove before rendering the rest. This is a brittle hack, and if we ever [change the order of the actions](https://github.com/dnadesign/silverstripe-elemental/pull/717) or add new ones, it'd likely break.

We should find an alternative approach for making this menu more extensible, and ideally add configuration allowing these actions to be easily disabled from the backend rather than necessitating intervention via JS.

Bears loose relation to the changes discussed in #403.

## Acceptance criteria
- The boilerplate elemental options are enabled or disabled based on the user permissions.
- There's a documented way to disabled publishing for blocks.

## Stretch goal
- Try to design a reusable API so the disabling can occur on custom elemental actions as well.

**Comment by chillu** [comment]
Note that I'm proposing we [disable block publishing by default](https://github.com/dnadesign/silverstripe-elemental/issues/756), and it sounds like this is on the critical path for achieving it.

**Comment by chrispenny** [comment]
Another use case is when a project is using [Advanced Workflow](https://github.com/symbiote/silverstripe-advancedworkflow). You need to be able to disable the publish button for the inline editor, otherwise authors can publish changes there, without needing to go through the workflow process.

The work around is to add a `canPublish()` that returns false to `BaseElement`, but this is not the best experience.

**Comment by emteknetnz** [comment]
IMO a good outcome is that a DataExtension is added at the project level that uses PermissionProvider and then site admins can edit which user groups can inline publish.  That would prevent the inline publish dropdown option from being presented

However the current user experienced (based on a Slack convo I had with Chris earlier), is that instead what happens is the inline publish option is still present, though when `false` is returned from `canPublish`, the user is presented with an ugly red toast that says something along the lines of "error".  Poor UX.

So seems like we need to feed the result of `canPublish` (and other relevant permissions) to javascript when building the react form, rather than only as a result when a publish is attempted

**Comment by maxime-rainville** [comment]
My main concern is that there might multiple ways devs might want to customise block actions. We won't be able to anticipate all of them.

My instinct would be to make the smallest possible change to allow customisation or deactivation of block actions in the main elemental module.

Then we could create a unsupported MVP module on the side to address the most common use case.

Once, we have a good idea of what the common scenarios are, maybe we fold them back into core.

**Comment by emteknetnz** [comment]
Pasting in part of the slack convo I had with @chrispenny 

`The workaround is to return false in the canPublish() of a block, but this does not remove the [publish] button from the Action Menu, and the "red toast" just says "error" (or something generic like that), so it's a really poor user experience.`

I'm a little confused here, there is JS code in PublishAction.js, UnpublishAction.js, ArchiveAction.js, DuplicateAction.js (and corresponding jest tests) to _disable_ the action menu components based on permissions, for instance I have the following:

```yml
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - MyBaseElementExtension
```

```php
<?php

use SilverStripe\ORM\DataExtension;

class MyBaseElementExtension extends DataExtension
{
    public function canPublish($member = null)
    {
        return true;
    }

    public function canUnpublish($member = null)
    {
        return false;
    }

    public function canCreate($member = null)
    {
        return true;
    }

    public function canDelete($member = null)
    {
        return false;
    }
}
```

And the inline block action menu on an element that's previously been published and now has more draft changes on it renders like this

![image](https://github.com/silverstripe/silverstripe-elemental/assets/4809037/9ee2126d-be5e-4237-818d-19c4d37cb8af)

I cannot click on the disabled options, so I'm not sure how we end up with a red toast with a generic error message?

We could change the behavior so that instead of disabling the options we simply don't render them, though I think I prefer this UI a little less.  Save/Publish/Unpublish/Archive/Duplicate is a very stable CMS paradigm so I'm generally fine with it being "hardcoded"

Given that things appear to be working correctly, to me it seems like projects using a combination of `can*` methods on extensions and `PermissionProvider`  to enable group permissions to be setup correctly provides an acceptable outcome?

**Comment by chrispenny** [comment]
Thanks, @emteknetnz!

I must admit that I hadn't tried this since (probably) `4.9`. That is definitely the sort of experience I was hoping for though. I think this gets us most (all?) of the way for our (personal) immediate needs. I think with this we can:

* Disable publishing/un-publishing/archiving through the inline editor when a Workflow is active.
* Ditto the above for projects that use Static Publisher (and prefer publishes are actioned from the Page edit form).

**Comment by emteknetnz** [comment]
OK sounds good, I'll mark this as closed for now.  If you later realise that there is still poor UX here then let me know on this issue and I'll reopen this
