### ISSUE TITLE
DOCS: How to implement multiple ElementalAreas

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental#759]
This seems to be the talk of the town at the moment 😛 

## Objective
- This repository includes some guiding documentation on how to implement multiple ElementalAreas within a page template. At the moment guidance is limited to these [inline comments](https://github.com/dnadesign/silverstripe-elemental/blob/4/src/Extensions/ElementalAreasExtension.php#L20-L42).
- Any limitations or known 'gotchas' are also described.

PRs welcome!

**Comment by mfendeksilverstripe** [comment]
I would avoid recommend implementing multiple elemental area on a page for following reasons:

* added complexity
* performance considerations
* need to customise CMS UI

I recognise that there are use cases where multiple elemental areas would be nice, but these cases can be covered by other means. I will list two examples from existing projects.

## Multiple elemental areas - flat list

Suppose you have a page which needs four elemental areas as shown on the picture.

![ea-flat](https://user-images.githubusercontent.com/26395487/81986184-78d3fa00-968b-11ea-923e-62d514619b8b.png)

Instead of actually using four elemental areas we will use only one elemental area and introduce an `AreaGroup` to each block which will indicate which area group does it belong to (top, left, right, bottom). Area group is set in block edit form in a standard way, alternatively a custom gridfield action can be added to quickly switch area group on a block via inline editing.

Altering the render is not that difficult as we provide simple block filtering methods based on the `AreaGroup`.

Example template:

```
<%-- Top area group --%>
<% if $TopGroup.Count > 0 %>
  <% loop $TopGroup %>
    $Me
  <% end_loop %>
<% end_if %>

<div class="row">
    <%-- Left area group --%>
    <% if $LeftContentGroup.Count > 0 %>
      <section class="col col--3-4 col--pos-1-2">
        <% loop $LeftContentGroup %>
          $Me
        <% end_loop %>
      </section>
    <% end_if %>

    <%-- Right area group --%>
    <% if $RightGroup.Count > 0 %>
        <aside class="col col--1-4 col--pos-2-2">
          <% loop $RightGroup %>
            $Me
          <% end_loop %>
        </aside>
    <% end_if %>
</div>

<%-- Bottom area group --%>
<% if $BottomGroup.Count > 0 %>
  <% loop $BottomGroup %>
    $Me
  <% end_loop %>
<% end_if %>

```

## Multiple elemental areas - nested list

Suppose you a page which needs to have nested elemental areas. This may be a quite common requirements as elemental area <-> block structure can match the frontend grid system.

Page
- Elemental Area
-- Layout block (represents grid row)
--- Elemental Area
---- Content block (represents grid column)

![ea-nested](https://user-images.githubusercontent.com/26395487/81986199-7f627180-968b-11ea-976d-033d65afadcc.png)

I recommend using `silverstripe-elemental-list` module for this case.

**Comment by michalkleiner** [comment]
I disagree with the recommendation to avoid multiple areas per page.

The module was changed to support this very possibility (of having multiple areas per page), it's already been suggested (via the inline comments) how to achieve that, so I'd suggest the simplest thing to do is to transform the code comments into a simple docs page, not trying to obscure/hide the publicly available interface.

Developers/agencies can decide (and test/measure) for themselves whether a performance impact is a real thing/a problem for them. Further guidance/raising the possible risk/impact can be part of the documentation.

If the module stick with the concept of "an elemental area belongs to a page", even though it's not technically limited to that, we don't need to cover the use case of using it to create nested lists of elements.

**Comment by kinglozzer** [comment]
I also disagree with recommending against using multiple elemental areas per page. We regularly use multiple areas, clients have no problem understanding how they work (we just put, for example, a “Sidebar” element area in its own tab, it’s easy to implement and we’ve had no performance issues from doing so.

**Comment by tractorcow** [comment]
Sometimes you also need to have fixed content (e.g. navigation, menus, widgets) between areas; There's no way to do that with a single area without giving the CMS author far too much control over the layout (which a good dev limits).

I am using multiple areas, but am struggling with how to limit different blocks to different areas also. If anyone has figured out how to do that I'd love to hear :)

**Comment by ScopeyNZ** [comment]
> I am using multiple areas, but am struggling with how to limit different blocks to different areas also. If anyone has figured out how to do that I'd love to hear :)

The `ElementalAreaField` has a property (and constructor arg) that limits this. There's a way you can configure this with yaml, but I can't remember if/how it can be scoped (off the top of my head) - the code for that is here though:

https://github.com/dnadesign/silverstripe-elemental/blob/50a6032b2ccd1b6bf08f5405b8f2502ca7ddfc73/src/Extensions/ElementalAreasExtension.php#L92-L138

**Comment by kinglozzer** [comment]
@ScopeyNZ The problem with that is that it pulls the config from the class the extension is applied to - so if you have 2 areas applied to the same DataObject, you can only have one setting for which blocks are allowed for both areas.

@tractorcow This is how I've been handling it:

```php
<?php

namespace App\Extensions\Elements;

use App\Model\Elements\ElementDocuments;
use App\Model\Elements\ElementNews;
use App\Model\Elements\ElementUpcomingEvent;
use DNADesign\Elemental\Extensions\ElementalPageExtension as CoreElementalPageExtension;
use DNADesign\Elemental\Forms\ElementalAreaField;
use DNADesign\Elemental\Models\ElementalArea;
use DNADesign\Elemental\Models\ElementContent;
use SilverStripe\Core\Config\Config;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Tab;

class ElementalPageExtension extends CoreElementalPageExtension
{
    private static $has_one = [
        'SidebarElementalArea' => ElementalArea::class
    ];

    private static $owns = [
        'SidebarElementalArea'
    ];

    private static $cascade_duplicates = [
        'SidebarElementalArea'
    ];

    private static $allowed_sidebar_types = [
        ElementNews::class,
        ElementContent::class,
        ElementDocuments::class,
        ElementUpcomingEvent::class
    ];

    /**
     * @param FieldList $fields
     */
    public function updateCMSFields(FieldList $fields): void
    {
        parent::updateCMSFields($fields);

        /** @var ElementalAreaField $sidebar */
        $sidebar = $fields->dataFieldByName('SidebarElementalArea');
        if ($sidebar) {
            $fields->removeByName('Sidebar');
            $fields->insertAfter('Main', Tab::create('Sidebar', 'Sidebar'));
            $fields->addFieldToTab('Root.Sidebar', $sidebar);

            // Limit what elements can be created in sidebar
            $allowedSidebarTypes = Config::inst()->get(__CLASS__, 'allowed_sidebar_types');
            $availableTypes = $sidebar->getTypes();
            foreach ($availableTypes as $class => $type) {
                if (!in_array($class, $allowedSidebarTypes)) {
                    unset($availableTypes[$class]);
                }
            }
            $sidebar->setTypes($availableTypes);
        }
    }
}
```

**Comment by tractorcow** [comment]
thanks @kinglozzer that's exactly what I needed!
