### ISSUE TITLE
Issues with updateBlockSchema on a Extension for ElementContent

### ISSUE THREAD

**Issue by hadlee-lineham-wundermanthompson** [silverstripe/silverstripe-elemental#940]
Has anyone had an issue when trying yo add to the content on the summary for the ElementContent?

using updateBlockSchema

```
public function updateBlockSchema($blockSchema)
    {
        $blockSchema['content'] = $this->owner->getCustomPersona();
        // $blockSchema['content'] = $this->owner->getSummary();
        
        return $blockSchema;
    }

**Comment by michalkleiner** [comment]
You need to pass the variable in by reference and it doesn't need to be returned from the method.

`public function updateBlockSchema(array &$blockSchema)`

**Comment by michalkleiner** [comment]
Hi @hadlee-lineham-wundermanthompson, thanks for taking the time to post to the issue tracker.

The issue tracker is reserved for reporting bugs and we don’t provide support via the issue tracker. There are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org/), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

I’ll close this issue now but if you find the problem is within the module (and can provide replication steps), feel free to reopen the issue.
